### ISSUE TITLE
Treebank Pull Requests

### ISSUE THREAD

**Issue by chrisdrymon** [perseids-publications/harrington-trees#5]
Do you accept pull requests for corrections to treebank annotations?

**Comment by zfletch** [comment]
Thanks for creating this issue, @chrisdrymon. It's a good question. We want to make it possible for people to improve the treebanks, but often the collections are copied from elsewhere and changes need to be backported.

I've just now created an issue in the base repository (https://github.com/perseids-publications/treebank-template/issues/67) based on it. Feel free to leave any comments or suggestions.
